### ISSUE TITLE
Problems with installation instructions

### ISSUE THREAD

**Issue by 1n17** [MyHush/hush#62] opened 2017-10-30 21:53 UTC
### Describe the issue
Running "sudo echo 'deb https://dl.bintray.com/myhush/hush/ hush main' >> /etc/apt/sources.list" errors with "permission denied: /etc/apt/sources.list". Using "echo 'deb https://dl.bintray.com/myhush/hush/ hush main' | sudo tee --append /etc/apt/sources.list.d/hush.list" works as expected.

Also "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61" should be executed with sudo otherwise it fails to install the key.

### Can you reliably reproduce the issue?
Yes

#### If so, please list the steps to reproduce below:
1. Follow the installation instructions
2. Observe the errors

### Expected behaviour
The repository should be added to sources and the key should install correctly.

**Comment by madbuda** [comment] 2017-10-31 01:49
It appears you do not have sudo rights on the machine you're installing on

Closing as this is not a bug or issue with code

**Closed by madbuda** 2017-10-31 01:49 UTC

**Comment by 1n17** [comment] 2017-10-31 06:32
Hi @madbuda,
i do have sudo permissions on that machine but the command is wrong, please see https://askubuntu.com/questions/185268/permission-denied-etc-apt-sources-list. As for the apt-key command it requires root permissions but the instructions don't tell you to run it with sudo. Please update the instructions accordingly.

**Comment by 1n17** [comment] 2017-10-31 10:58
![installation](https://user-images.githubusercontent.com/33235498/32220517-57304efa-be32-11e7-9850-566c4aa1f094.png)

@madbuda, please see the image, I don't know how to explain it better.

**Comment by madbuda** [comment] 2017-10-31 11:05
What version of Ubuntu, sudo, what shell and version?

Hundreds  of installs and this is the first someone has had a problem with the installation instructions. I've personally installed using copy/paste many times myself and wrote the instructions

**Comment by 1n17** [comment] 2017-10-31 11:20
**cat /etc/*-release**
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**ps -p $$**
  PID TTY          TIME CMD
    2 tty1     00:00:00 bash

**apt-cache policy sudo**
sudo:
  Installed: 1.8.16-0ubuntu1.5

**apt-cache policy bash**
bash:
  Installed: 4.3-14ubuntu1.2

**Comment by 1n17** [comment] 2017-10-31 16:12
More info:
https://stackoverflow.com/questions/40292676/pipe-command-with-sudo
https://stackoverflow.com/questions/82256/how-do-i-use-sudo-to-redirect-output-to-a-location-i-dont-have-permission-to-wr
https://unix.stackexchange.com/questions/106663/how-do-you-process-an-entire-command-as-sudo-that-involves-redirecting-or-piping

The most common suggestion is to use tee:
echo 'deb https://dl.bintray.com/myhush/hush/ hush main' | sudo tee --append /etc/apt/sources.list.d/hush.list

**Comment by 1n17** [comment] 2017-11-17 21:14
Pretend there is no issue, ignore the person trying to help, and just silently correct the problem https://github.com/MyHush/hush/commit/01a2889f6b7b628b23c0ce9b5f949d00b7de6edb#diff-7d442b7eb49f5fc377f51e74b291cfc1... Way to go @madbuda!

**Comment by 1n17** [comment] 2017-11-17 21:19
Oh, by the way, there is still no sudo before apt-key command. But go ahead and pretend this is not a problem :D

**Comment by madbuda** [comment] 2017-11-17 23:21
Sorry, you reported an issue and we corrected it. If there are further corrections you'd like feel free to submit a PR with the proposed changes
